<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-TF9C2EJ" name="com.training.sanity.tests.UNF_090_AddingProduct_RewardPoints_Test" tests="4" failures="0" timestamp="05 Mar 2019 19:10:45 GMT" time="70.147" errors="1">
  <testcase name="addProductWithRewardPoints" time="35.731" classname="com.training.sanity.tests.UNF_090_AddingProduct_RewardPoints_Test">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.training.pom.UNF_090_Products_POM.setCategory_LinkTab_ProductLnk_CatalogIcn(UNF_090_Products_POM.java:117)
at com.training.sanity.tests.UNF_090_AddingProduct_RewardPoints_Test.addProductWithRewardPoints(UNF_090_AddingProduct_RewardPoints_Test.java:86)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- addProductWithRewardPoints -->
  <testcase name="addProductWithRewardPoints" time="12.325" classname="com.training.sanity.tests.UNF_090_AddingProduct_RewardPoints_Test"/>
  <testcase name="addProductWithRewardPoints" time="10.021" classname="com.training.sanity.tests.UNF_090_AddingProduct_RewardPoints_Test"/>
  <testcase name="addProductWithRewardPoints" time="12.070" classname="com.training.sanity.tests.UNF_090_AddingProduct_RewardPoints_Test"/>
</testsuite> <!-- com.training.sanity.tests.UNF_090_AddingProduct_RewardPoints_Test -->
